name: 📘 Deploy MkDocs

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install MkDocs
        run: |
          pip install \
            mkdocs==1.6.0 \
            mkdocs-material==9.5.21 \
            mkdocs-github-admonitions-plugin==0.1.1 \
            mkdocs-glightbox

      - name: Build MkDocs
        run: mkdocs build

      - name: Add CNAME
        run: |
          echo "docs.netalertx.com" > site/CNAME

      - name: Deploy MkDocs
        run: mkdocs gh-deploy --force
